INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("Some Taco Trucks", "Tron Martinez", "Colpa Press, Street Salad", 2020, "In the Fall of 2016, a seemingly innocuous statement by a supporter of then-candidate Trump became an instant political meme. The co-founder of Latinos for Trump, Marco Gutierrez explained, 'My culture is a very dominant culture. It is imposing and it’s causing problems. If you don’t do something about it, you’re going to have taco trucks [on] every corner. His dog-whistle rhetoric aside, this latent racism is nothing new. In 2005, Latinx workers flocked to New Orleans for reconstruction work after Hurricane Katrina. Unsurprisingly, taco trucks began operating to feed those workers. In response, Jefferson Parish passed legislation, effectively banning taco trucks to discourage the influx of Latinx workers. Originally, taco trucks served predominantly working-class Latinx communities, setting up in parking lots, near factories and soccer fields. Recently, taco trucks have become locations of culinary tourism for diners in search of ethnic exoticism. Gentrified taco trucks can now be seen in upscale neighborhoods and corporate centers. The pursuit of authentic tacos and taco trucks contains its own cultural politics, a democratic acknowledgment of blue-collar food. However, even that space is in jeopardy with the rise of food delivery apps. Diners can now remain at home without having to interact with the working-class people making their food. Now, customers merely tap their screens and, eventually nod to an anonymous (usually POC) delivery person. Here, a series of Bay Area taco trucks serve as a reminder of the immigrant entrepreneurs and the communities they create with their trucks, both culinary and physical.", "https://cdn.shopify.com/s/files/1/0190/8668/products/taco_doc1_2a3a79e6-ab01-4ab5-ac86-271057c65f12_1024x1024.png?v=1604507143", "2022-10-06 10:25:42.517205-07");

INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("Diabolus Ex Machina", "David Kaspbrzak", "Colpa Press", 2020, "A sequel to Reel Estate Times, Movie Memory is a collage book that looks at how art and film can shape our collective memory.", "https://cdn.shopify.com/s/files/1/0190/8668/products/exmachina1_1024x1024.png?v=1606961217", "2022-10-06 10:25:42.517205-07");

INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("Movie Memory", "Mitsu Okubo, Luca Antonucci", "Colpa Press", 2020, "Diabolus Ex Machina is a collection of images found in early computer sales brochures stripped of all of their text. Ironically, these images are appealing because of their handmade/analog techniques rather than being produced by the machines they promote. The book documents both the sensational and banal marketing aimed at convincing us to bring these machines into our offices and eventually our homes — for better or worse.", "https://cdn.shopify.com/s/files/1/0190/8668/products/movie_memory_1024x1024.png?v=1576290546", "2022-10-06 10:25:42.517205-07");

INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("Sinkholes of Florida", "Kathleen Saunders", "Drum Machine Editions", 2020, "Kathleen Saunders (Charleston, SC) is a photographer who frequently returns to Florida's natural springs. Her work engages both the environmental precarity and history of kitschy tourism surrounding the state's once-pristine aquifers. She has interviewed local historians and retired mermaids and pored over dense water quality studies. In her riso-printed photobook, Sinkholes of Florida, Saunders distills this body of work into a deadpan collection of found images which oscillate between humor and dread.", "https://freight.cargo.site/w/1000/i/10d98b0ba0489619373b02b040b8eafa1592ab26051075f1a4c08f09bb4b2dce/SINKHOLES_COVER.jpg", "2022-10-06 10:25:42.517205-07");

INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("Protection Rituals", "Rita Mookerjee, Wade Tullier", "Drum Machine Editions", 2020, "Protection Rituals is a collection of drawings and ekphrastic poems by Wade Tullier (Detroit, Michigan) and Rita Mookerjee (Chicago IL). Tullier’s spare, archetypal assemblages are in constant motion, casting long shadows over Mookerjee’s defiant narrator. Velvet couches, salt lines, late-70s Bowie, and egg-topped ramen provide an indulgent backdrop for the twelve examinations of adolescence, ennui, and loneliness contained in this genre-bending collection.", "https://freight.cargo.site/w/1000/i/0643fae2a812bcdf2e198da872ff6985c9287f5fabce80b70b1a4b222fe612a4/RITUALS_01.jpg", "2022-10-06 10:25:42.517205-07");

INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("Oslofjord", "Jessica Williams", "Issue Press", 2022, "This second and expanded edition of Jessica Williams' (US/NO) 'Oslofjord' is a close collaboration between the artist and Issue Press. Images have been both reworked and added on the five year anniversary of the original publication. In 2016 the artist started seeing and collecting a very odd type of beach plastic on the islands off the inner Oslofjord in Norway. This book is her collection: an oddly aesthetic and terrifying testament to the carelessness of humans and the relentless force which is nature.", "https://cdn.shopify.com/s/files/1/0268/1772/4598/products/oslofjord-page-10-11.png?v=1653368308", "2022-10-06 10:25:42.517205-07");

INSERT INTO main_app_book(title, artist, publisher, release_year, description, image, created_at)
    VALUES("How to Art Book Fair", "Paul Shortt", "Shortt Editions", 2021, "How to art book fair features advice on how to plan, participate, and succeed in an art book or zine fest. This second expanded edition features sections on pricing, selling, table layout, being a good tablemate, talking to fair organizers, trading, and more. With extra advice from over 15 art book fair experts, this book will guide you through everything you need to table at an art book fair. The book also now features one bonus page that gives advice on How to Virtually Art Book Fair and How To Participate post-Covid-19. The book features advice from: Amber Eve Anderson, Alison Baitz, Amy Burek, Ethan Crenson, Celeste Fichter, Marc Fischer, Paul John, Christopher Kardambikis, Gary Kachadourian, Antoine Lefebvre, Leah Mackin, Michalis Pichler, Daniel Spottswood, Daphne Taranto, Panayiotis Terzis, Anthony Tino, Andrew Jeffrey Wright.", "https://assets.bigcartel.com/product_images/244443002/IMG_1363_web_crop.jpg?auto=format&fit=max&w=1200", "2022-10-06 10:25:42.517205-07");